//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UtilityTool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Power_Shutdown_SG_ctr {
            get {
                return ((int)(this["Power_Shutdown_SG_ctr"]));
            }
            set {
                this["Power_Shutdown_SG_ctr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Power_Shutdown_S_ctr {
            get {
                return ((int)(this["Power_Shutdown_S_ctr"]));
            }
            set {
                this["Power_Shutdown_S_ctr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Power_Restart_G_ctr {
            get {
                return ((int)(this["Power_Restart_G_ctr"]));
            }
            set {
                this["Power_Restart_G_ctr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Power_Restart_R_ctr {
            get {
                return ((int)(this["Power_Restart_R_ctr"]));
            }
            set {
                this["Power_Restart_R_ctr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Power_Hibernate_H_ctr {
            get {
                return ((int)(this["Power_Hibernate_H_ctr"]));
            }
            set {
                this["Power_Hibernate_H_ctr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Power_Quickstart_Hybrid_ctr {
            get {
                return ((int)(this["Power_Quickstart_Hybrid_ctr"]));
            }
            set {
                this["Power_Quickstart_Hybrid_ctr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Power_Signoff_L_ctr {
            get {
                return ((int)(this["Power_Signoff_L_ctr"]));
            }
            set {
                this["Power_Signoff_L_ctr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05/05/2018 14:08:00")]
        public global::System.DateTime Power_Shutdown_SG_date {
            get {
                return ((global::System.DateTime)(this["Power_Shutdown_SG_date"]));
            }
            set {
                this["Power_Shutdown_SG_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05/05/2018 14:08:00")]
        public global::System.DateTime Power_Shutdown_S_date {
            get {
                return ((global::System.DateTime)(this["Power_Shutdown_S_date"]));
            }
            set {
                this["Power_Shutdown_S_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05/05/2018 14:08:00")]
        public global::System.DateTime Power_Restart_G_date {
            get {
                return ((global::System.DateTime)(this["Power_Restart_G_date"]));
            }
            set {
                this["Power_Restart_G_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05/05/2018 14:08:00")]
        public global::System.DateTime Power_Restart_R_date {
            get {
                return ((global::System.DateTime)(this["Power_Restart_R_date"]));
            }
            set {
                this["Power_Restart_R_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05/05/2018 14:08:00")]
        public global::System.DateTime Power_Hibernate_H_date {
            get {
                return ((global::System.DateTime)(this["Power_Hibernate_H_date"]));
            }
            set {
                this["Power_Hibernate_H_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05/05/2018 14:08:00")]
        public global::System.DateTime Power_Quickstart_Hybrid_date {
            get {
                return ((global::System.DateTime)(this["Power_Quickstart_Hybrid_date"]));
            }
            set {
                this["Power_Quickstart_Hybrid_date"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("05/05/2018 14:08:00")]
        public global::System.DateTime Power_Signoff_L_date {
            get {
                return ((global::System.DateTime)(this["Power_Signoff_L_date"]));
            }
            set {
                this["Power_Signoff_L_date"] = value;
            }
        }
    }
}
